name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: mlkmahmud
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export PROJECT_VERSION=$(git describe --tags)
            /bin/bash sample_deploy.sh
